//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.25 at 08:18:21 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://online_market.market.spring.com/soap/productsWs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spring.market.online_market.soap.productsws;
